apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: wordpress-main
spec:
  ports:
#    - protocol: TCP
    - port: 3306
      targetPort: 3306
  selector:
    app: wordpress-main
    tier: mysql
  clusterIP: None
