apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wordpress-main
  labels:
    app: wordpress-main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-main
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress-main
        tier: frontend
    spec:
      nodeSelector:
        disktype: worker
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim

      containers:
      - name: wordpress-main
        image: wordpress:5.1.1-php7.3-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var          
