apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wordpress-main
  labels:
    app: wordpress-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-main
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress-main
        tier: frontend
    spec:
      nodeSelector:
        disktype: worker  
      containers:
      - name: wordpress-main
        image: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: databaseName
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim

