apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress-main
  type: LoadBalancer
  ports:
  #  - protocol: TCP
   -  port: 80
      targetPort: 80
      nodePort: 30050
